### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by james2doyle**

### CODE REVIEW

**Comment by manavo** [comment]
Sorry my pull requests have caused a conflict here @tvercruysse, happy to help resolve them if necessary!

**Comment by james2doyle** [comment]
I opened these changes myself from that fork and branch of this project. They are not from the original user.

I haven't really had time to review the changes. If you feel they would be useful and you have time that would be really helpful

**Comment by manavo** [comment]
Ah, OK! I was a bit confused with the PR opened by you but the commits being from someone else!

I'm guessing I can fork the fork, then open a new PR here which could replace this one. I'll try that out and see!

**Comment by james2doyle** [comment]
psonic is not ready for prime time

**Comment by tvercruysse** [comment]
I forked this repo a while ago when i was experimenting with sonic, but never tried to make it stable in any way.
However sonic still interests me and i might put in some work into this library to make it more reliable and up-to-date.

**Comment by manavo** [comment]
@tvercruysse I also did a bit of extra work on this, it's sitting in #8 at the moment!

**Comment by tvercruysse** [comment]
> @tvercruysse I also did a bit of extra work on this, it's sitting in #8 at the moment!

Great to see movement! I previously bailed because both psonic (official) and php-sonic (community) were rather unmaintained and buggy at the time. After an hour of debugging and experimenting i lost interest and stuck with elasticsearch.

Maybe an issue with a checklist of what works and what doesn't yet would help dev's contribute without being discouraged.

Opinions ?

**Comment by manavo** [comment]
Would probably be good, but I'm pretty sure #8 is ready and fully functional. Some PRs were required upstream to psonic, but those are all merged and work fine!

Another pair of eyes and some tests would definitely help to make sure #8 is stable, but not sure there's much else for a checklist other than that?

**Pull request closed without merging**
