### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by manavo**
This can replace #4, it includes the same commits but is up to date with `master`

### CODE REVIEW

**Comment by manavo** [comment]
The changes themselves are untested for now, so I'll look at that next

**Comment by manavo** [comment]
Having some issues with `psonic`, so trying to work those out first. I've [got a pull request upstream](https://github.com/ppshobi/psonic/pull/18) to fix one of the issues I've found so far, but for now this probably shouldn't be merged.

**Comment by manavo** [comment]
Based on my tests so far, my hunch is that sticking with php-sonic might be better. Just my opinion though!

**Comment by james2doyle** [comment]
OK, I'm fine with that. What makes you think it's worth sticking to though?

**Comment by manavo** [comment]
Better configuration (like read timeout), and getting fewer errors out of it. I tried putting the branch live with psonic, and got a whole bunch of errors. Not sure why that was as I haven't debugged them yet, but right now php-sonic seems to work better (at least in my use case).

It is an extreme use case I have right now (trying to import ~7 million objects) so it is heavy load, but php-sonic works, and psonic doesn't 🤷 

If I get some more time I'll try to debug it, but since php-sonic works it's hard to prioritize 🙁

**Comment by james2doyle** [comment]
Ok so you think its worth just sticking with php-sonic for now. So we can close this then?

**Comment by manavo** [comment]
Yep, closing this now, and can probably close #4 too?

**Comment by james2doyle** [comment]
Great! Thanks for the PRs!

**Comment by manavo** [comment]
Made the time to dig into this some more, and it was just 1 other little bug which was causing all the issues.

[I've submitted a PR](https://github.com/ppshobi/psonic/pull/19) to psonic to fix it, so once that's merged I think this should be good to go too!

**Comment by manavo** [comment]
The main reason for looking into this again is to add support for language/locale in `PUSH` commands. Not included in this PR, but at least `psonic` supports locale whereas `php-sonic` doesn't.

And the `psonic` maintainer seems more responsive to PRs than `php-sonic` 🙂

**Comment by manavo** [comment]
I forgot I left this as a draft! I think this is OK and stable, but if you have some time to test it as well that would definitely be good @james2doyle!

**Pull request merged**
